kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: maven:latest
    commands:
      - mvn clean package verify
#  - name: build docker
#    image: a voir
#    commands:
#      - docker-compose up --build


trigger:
  branch:
    - master
  event:
    - push
    - cron
