version: '3'
services:


  ############  MANAGE ENTERPRISE ACCOUNTS  #################

  warehouse-server:
    container_name: creadirama-manage-enterprise-accounts-server
    build:
      context: warehouse
      dockerfile: Dockerfile
      args:
        JAR_FILE: target/warehouse-0.0.1-SNAPSHOT.jar
    image: creadirama-manage-enterprise-accounts-server:latest
    expose:
      - 8081
    ports:
      - 8081:8080
    networks:
      - creadirama-network
    logging:
      driver: json-file
    depends_on:
      - kafka
      - kafka-awaiter

    environment:
      NOTIFICATION_HOST: notification
      DRONE_HOST: http://drone-server:8080
      KAFKA_HOST: http://kafka:9092