version: '3'
services:


  ############  MANAGE ENTERPRISE ACCOUNTS  #################

  mea-server:
    container_name: credirama-manage-enterprise-accounts-server
    build:
      context: manageEntrepriseAccounts
      dockerfile: Dockerfile
      args:
        JAR_FILE: target/manageEntrepriseAccounts-1.0-SNAPSHOT.jar
    image: credirama-manage-enterprise-accounts-server:latest
    expose:
      - 8081
    ports:
      - 8081:8081
    logging:
      driver: json-file
    networks:
      - credirama-network


  ############ PRETTY DUMP  #################

  prettydump-server:
    container_name: credirama-pretty-dump-server
    build:
      context: PrettyDump
      dockerfile: Dockerfile
      args:
        JAR_FILE: target/PrettyDump-1.0-SNAPSHOT.jar
    image: credirama-pretty-dump-server:latest
    expose:
      - 8085
    ports:
      - 8085:8085
    logging:
      driver: json-file
    networks:
      - credirama-network
    environment:
      MEA: http://mea-server:8081
      TRANSACTION: http://transaction-server:8084


  ############ TRANSACTIONS  #################

  transaction-server:
    container_name: credirama-transaction-server
    build:
      context: Transaction
      dockerfile: Dockerfile
      args:
        JAR_FILE: target/transaction-1.0-SNAPSHOT.jar
    image: credirama-transaction-server:latest
    expose:
      - 8084
    ports:
      - 8084:8084
    logging:
      driver: json-file
    networks:
      - credirama-network
    environment:
      MEA: http://mea-server:8081


  ############ ANALYSE DATA  #################

  analyse-data-server:
    container_name: credirama-analyse-data-sever
    build:
      context: AnalyseData
      dockerfile: Dockerfile
      args:
        JAR_FILE: target/AnalyseData-1.0-SNAPSHOT.jar
    image: credirama-analyse-data-server:latest
    expose:
      - 8088
    ports:
      - 8088:8088
    logging:
      driver: json-file
    networks:
      - credirama-network
    environment:
      TRANSACTION: http://transaction-server:8084

  ############ DEPENDENCIES #################

  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - analyse-data-server
      - mea-server
      - prettydump-server
      - transaction-server
    command: analyse-data-server:8088 mea-server:8081 prettydump-server:8085 transaction-server:8084
    networks:
      - credirama-network

networks:
  credirama-network:
    driver: bridge
