version: '3'
services:

  ############  MANAGE ENTERPRISE ACCOUNTS  #################

  mea-server:
    container_name: credirama-manage-enterprise-accounts-server
    build:
      context: manageEntrepriseAccounts
      dockerfile: Dockerfile
      args:
        JAR_FILE: target/manageEntrepriseAccounts-1.0-SNAPSHOT.jar
    image: credirama-manage-enterprise-accounts-server:latest
    expose:
      - 8081
    ports:
      - 8081:8080
    logging:
      driver: json-file


  ############ PRETTY DUMP  #################

  prettydump-server:
    container_name: credirama-pretty-dump-server
    build:
      context: PrettyDump
      dockerfile: Dockerfile
      args:
        JAR_FILE: target/PrettyDump-1.0-SNAPSHOT.jar
    image: credirama-pretty-dump-server:latest
    expose:
      - 8085
    ports:
      - 8085:8080
    logging:
      driver: json-file

    environment:
      NOTIFICATION_HOST: notification
      DRONE_HOST: http://drone-server:8080
      KAFKA_HOST: http://kafka:9092